name: Bluefin Stable ISO
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '41 6 * * 2'  # 6:41 UTC every Tuesday
  

jobs:
  build-latest:
    name: Bluefin GTS
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    with:
      brand_name: bluefin
      fedora_version: gts
      image_flavor: main
